# Tutorial mathlab

# .TS (matrix)
 - Транспонирование 1-й матрицы
 
# .T (list_matrix)
 - Транспонирование n матриц

# .det (matrix)
- Нахождение определителя матрицы

# .M (matrix1, matrix2)
 - Перемножение 2-х матриц
 
# .MS (matrix, k)
- Умножение матрицы на скаляр
     - k -число, на которое надо умножить матрицу

# .dot (list_matrix, n)
 - Перемножение n матриц
 
# .multiply(list_matrix, n, k)
- Умножение n матриц на скаляр

     - k -число, на которое надо умножить матрицу
     - n - количество матриц
     - list_matrix - массив матриц
    
# .divide(list_matrix, n, k):
- Деление матриц
     - k -число, на которое надо разделить матрицу
     - n - количество матриц
     
# .mininmum(list_matrix, number):
 - Минимальный элемент конкретной матрицы
      - number - номер матрицы в списке
     
# .maximum(list_matrix, number):
 - Максимальный элемент конкретной матрицы
      - number - номер матрицы в списке

# .add(list_matrix, n)
- Сложение матриц
     - n - количество матриц, которые надо сложить

# .subtract(list_matrix, n, number)
 - Вычитание матриц
      - n - количество матриц, которые надо вычесть
      - number - матрица, из которой нужно вычесть все остальные
    

# .Jacobi(A, B, accurancy)
- нахождение СЛАУ
        A - матрица
        B - значения
        accurancy - точность

# .Jordan_Gauss(A, B)
- нахождение СЛАУ

# .Jordan_Gauss_proper(A, B)
- нахождение СЛАУ



In [1]:
import numpy as np
import pandas as pd
import mathlab

# Ввод 1:  руками

In [2]:
complex_matrix = np.array([[-9 + 7j, 35, 8- 3j], [5, -4 - 1j, 20], [8, 2j, 7+ 2j]])
l = np.array([[4,0],[2, 7], [4, 6]])
mt = np.array([[-2, 2], [6, -6]])
list_of_massiv = [np.array([[1j, 2], [89j, 5]]), np.array([[-8, 4+5j], [3, -3]]), np.array([[6j, 8], [44, -7+2j]])]
m1 = np.array([[1, 2, 6], [8, 8, 2], [9, 23, 0]])
m2 = np.array([[12, 5], [6, 8], [31, 9]])
list_massiv2 = [np.array([[1, 23, 56, 7j],[-5, 16, 5, (39-5j)],[6j, (7+8j), 99, 23]]), 
                         np.array([[1, 4, 63, -89],[-3, 6, 4j, (5+2j)],[3, 1, 46, 91]]),
                         np.array([[4j, (7+3j), (9-9j), 2], [9, 36, 82, 19],[-5, -8, -99, (4-7j)]])]
                         


In [3]:
A = np.array([[10., -1., 2., 0.],
 [-1., 11., -1., 3.],
 [2., -1., 10., -1.],
 [0.0, 3., -1., 8.]])
# initialize the RHS vector
B = np.array([6., 25., -11., 15.])

A = np.array([[2.6, -1.7, 2.5],
             [1.5, 6.2, -2.9],
             [2.8, -1.7, 3.8]])
B = np.array([3.7, 3.2, 2.8]) 

# Ввод 2 : генерируем

In [4]:
import numpy as np
# сгенерированная матрица
np.random.uniform(low=-100, high=100, size=(3, 3))

array([[ 39.50978368, -22.62633092,  58.0215262 ],
       [-98.67197832,   3.60704466, -95.24245952],
       [ 87.64039108, -21.86818107, -12.36706579]])

# Ввод 3 : для n матриц с клавиатуры (включая комплексные числа)

In [ ]:
import sqlite3
from sqlite3 import connect
conn = connect(':memory:')

In [ ]:
def dimension():
    s = list(map(int, input('Введи размерность: ').split()))[0]
    r = list(map(int, input('Введи размерность: ').split()))[0]
    return s, r

In [ ]:
# считываем массив с клавиатуры
def read_massiv(n):
    st, rw = dimension()
    for matrx in range(n):
        massiv = []
        for j in range(st):
            string = list(map(str, input('Введи строку: ').split()))
            massiv.append(string)
        massiv = pd.DataFrame(np.array(massiv))
        massiv.columns = [f'{k}' for k in range(rw)]
        print(massiv)
        # записываем в БД
        massiv.to_sql(f'matrix_frame{matrx}', conn, index_label='id')


In [ ]:
from copy import*
from copy import deepcopy

def remember_matrix(matrix):
    matrix1 = deepcopy(matrix)
    return matrix1


def take_matrix(n):
    # вводим размерность и матрицы
    read_massiv(n)
    
    new_matrix = []
    for k in range(n):
       
        small_new_matrix = []
        conn.execute(f'SELECT  * FROM matrix_frame{k}').fetchall()
        conn.row_factory = sqlite3.Row   
        cursor = conn.execute(f'SELECT * FROM matrix_frame{k}')
        for row in cursor:
            small_new_matrix.append(row[1:])
         
        small_new_matrix = pd.DataFrame(small_new_matrix)
        small_new_matrix = np.array(small_new_matrix)
        # преобразуем str в complex
       
        print(f'matrix num {k+1}: {small_new_matrix}')
        new_matrix.append(remember_matrix(small_new_matrix))
    str_matrix = deepcopy(new_matrix)
    
    # str into complex
    
    for massiv in (new_matrix):    
        for i in range(len(massiv)):
            for z in range(len(massiv[0])):
                if 'j' in massiv[i][z]:
                    massiv[i][z] = complex(massiv[i][z])
                else:
                    massiv[i][z] = eval(massiv[i][z])
                
                

    return new_matrix, str_matrix     

    
list_massiv = take_matrix(1)  
list_massiv[1]

In [ ]:
list_massiv[0]

# Удалить таблицу к чертям

In [ ]:
import sqlite3

for i in range(n):
    conn = sqlite3.connect(f'matrix_frame{i}')
    c = conn.cursor()
    # delete all rows from table 
    c.execute(f'DELETE FROM matrix_frame{i}',); 
    #commit the changes to db conn.commit() #close the connection conn.close()


In [ ]:
conn = sqlite3.connect(f'matrix_frame0')
cur = conn.cursor()
cur.execute('SELECT * FROM matrix_frame0 WHERE type = "table"')
while True:
    row = cur.fetchone()
    print(row)
    if row == None:
        break

# Ввод 4:  для 1 матрицы с клавиатуры

In [ ]:
#вводим размерность
try:
    d = list(map(int, input('Введи размерность: ').split()))
except ValueError:
    print('введи адекватное число')
d = d[0]

In [ ]:
# считываем массив с клавиатуры
try:
    num = [list(map(complex, input('Введи строку: ').split())) for i in range(d)]
except ValueError:
     print('введи адекватное число')
    
    
num = np.array(num)

In [ ]:
from time import perf_counter

# Ввод 5. Tkinter. Запись в html, txt, csv

In [ ]:
import tkinter as tk
import sys
from tkinter.filedialog import asksaveasfilename
import pymysql
 
def save_file_as():
    filepath = asksaveasfilename(
        defaultextension = "txt",
        filetypes = [("Текстовые файлы", "*.txt"), ("HTML файлы", "*.html"), ("CSV файлы", "*.csv")]
        )
    if not filepath:
        return
    with open(filepath, "w", encoding = "UTF-8") as output_file:
        text = txt_edit.get("1.0", tk.END)
        output_file.write(text)
    window.title(f"Work with - {filepath}")
    
def exit():
    window.after(1,window.destroy)
    sys.exit

 
window = tk.Tk()
window.title("Save text")
 
window.rowconfigure(0, minsize = 50, weight = 1)
window.columnconfigure(1, minsize = 50, weight = 1)
 
txt_edit = tk.Text(window)
fr_buttons = tk.Frame(window)
fr_buttons2 = tk.Frame(window)


btn_save = tk.Button(fr_buttons, text = "Save file_as", command = save_file_as)
btn_exit = tk.Button(fr_buttons2, text = "Exit", command = exit)

 
btn_save.grid(row = 0, column = 0, padx = 5, pady = 5)
btn_exit.grid(row = 0, column = 0, padx = 5, pady = 5)


fr_buttons.grid(row = 0, column = 0, sticky = "ne")
fr_buttons2.grid(row = 1, column = 0, sticky = "ne")


txt_edit.grid(row = 0, column = 1)
 
window.mainloop()

Выделяем A, B

In [5]:
def to_proper_fraction(massiv):

    A1 = np.zeros_like(massiv)
    for i in range(len(massiv)):
        for j in range(len(massiv[0])):
            if '/' in massiv[i][j]:
                if massiv[i][j][0] == '-':
                    left_digit = int(massiv[i][j][1:massiv[i][j].index('/')])
                    right_digit = int(massiv[i][j][massiv[i][j].index('/')+1:])
                    fraction = sym.Rational(left_digit, right_digit)
                    A1[i][j] = fraction
                else:
                    left_digit = int(massiv[i][j][:massiv[i][j].index('/')])
                    right_digit = int(massiv[i][j][massiv[i][j].index('/')+1:])
                    fraction = sym.Rational(left_digit, right_digit)
                    A1[i][j] = fraction
            else:
                A1[i][j] = int(massiv[i][j])
    return A1

In [6]:
import pandas as pd
import numpy as np
import sympy as sym
df = pd.read_csv('matrix.csv', delimiter=' ', header = None)
df2 = pd.read_csv('bad_matrix.csv', delimiter=' ', header = None)
print(df)
print(df2)


A = df.loc[:, :len(df)-1]
A = np.array(A)
B = df.loc[:, len(df):len(df)]
B = np.array(B)
A1 = df2.loc[:, :len(df2)-1]
A1 = np.array(A1)
B1 = df2.loc[:, len(df2):len(df2)]
B1 = np.array(B1)
x = np.zeros_like(B)

K = np.column_stack((A1, B1))
C = to_proper_fraction(K)
C = np.array(C).astype(np.float32)
A2 = C[:, :len(C)]
B2 = C[:, len(C):]


A1

     0    1    2    3
0  2.6 -1.7  2.5  3.7
1  1.5  6.2 -2.9  3.2
2  2.8 -1.7  3.8  2.8
           0          1          2
0  1001/1000  2001/1000          4
1  2001/1000  3998/1000  7999/1000


array([['1001/1000', '2001/1000'],
       ['2001/1000', '3998/1000']], dtype=object)

# Вывод

In [7]:
mathlab.TS(l)

array([[4, 2, 4],
       [0, 7, 6]])

In [8]:
mathlab.T(list_massiv2)

[array([[ 1.+0.j, -5.+0.j,  0.+6.j],
        [23.+0.j, 16.+0.j,  7.+8.j],
        [56.+0.j,  5.+0.j, 99.+0.j],
        [ 0.+7.j, 39.-5.j, 23.+0.j]]),
 array([[  1.+0.j,  -3.+0.j,   3.+0.j],
        [  4.+0.j,   6.+0.j,   1.+0.j],
        [ 63.+0.j,   0.+4.j,  46.+0.j],
        [-89.+0.j,   5.+2.j,  91.+0.j]]),
 array([[  0.+4.j,   9.+0.j,  -5.+0.j],
        [  7.+3.j,  36.+0.j,  -8.+0.j],
        [  9.-9.j,  82.+0.j, -99.+0.j],
        [  2.+0.j,  19.+0.j,   4.-7.j]])]

In [9]:
mathlab.det(mt)

[[-2  2]
 [ 6 -6]]
Singular matrix


0

In [10]:
mathlab.M(m1, m2)

[[210  75   0]
 [206 122   0]
 [246 229   0]]


In [11]:
mathlab.MS(m1, 32)

array([[ 32,  64, 192],
       [256, 256,  64],
       [288, 736,   0]])

In [12]:
mathlab.dot(list_of_massiv, 2)

C:\Users\valen\Moduls\mathlab.py:110: ComplexWarning: Casting complex values to real discards the imaginary part
  matrix3[i,j] += empty_matrix_list[i, k] * list_matrix[t][k, j]


array([[  6,  -6],
       [ 15, -15]])

In [13]:
mathlab.multiply(list_massiv2, 2, 5)

[array([[  5. +0.j, 115. +0.j, 280. +0.j,   0.+35.j],
        [-25. +0.j,  80. +0.j,  25. +0.j, 195.-25.j],
        [  0.+30.j,  35.+40.j, 495. +0.j, 115. +0.j]]),
 array([[   5. +0.j,   20. +0.j,  315. +0.j, -445. +0.j],
        [ -15. +0.j,   30. +0.j,    0.+20.j,   25.+10.j],
        [  15. +0.j,    5. +0.j,  230. +0.j,  455. +0.j]])]

In [14]:
mathlab.divide(list_massiv2,0, 5)

[]

In [15]:
mathlab.add(list_massiv2, 2)

C:\Users\valen\Moduls\mathlab.py:173: ComplexWarning: Casting complex values to real discards the imaginary part
  empty_matrix_list[i][j] +=  matrix[i][j]


array([[  2,  27, 119, -89],
       [ -8,  22,   5,  44],
       [  3,   8, 145, 114]])

In [16]:
mathlab.subtract(list_massiv2, 3, 0)

array([[  0.-4.j,  12.-3.j, -16.+9.j,  87.+7.j],
       [-11.+0.j, -26.+0.j, -77.-4.j,  15.-7.j],
       [  2.+6.j,  14.+8.j, 152.+0.j, -72.+7.j]])

In [17]:
mathlab.mininmum(list_massiv2, 0)

9223372036854775807


(-77-4j)

In [18]:
mathlab.maximum(list_massiv2, 1)

(91+0j)

# Jacobi

In [19]:
mathlab.Jacobi(A2, B2, 0.001)

Matrix:
1.0010000467300415*x1 + 2.000999927520752*x2 = [4.]
2.000999927520752*x1 + 3.997999906539917*x2 = [7.999]
матрица плохо обусловлена 0.0


(' норма матрицы: 4.999400540677136',
 ' норма обратной матрицы: 0.0, решение:',
 array([[-1.986687  ],
        [ 0.42571327]], dtype=float32),
 array([[-0.,  0.],
        [ 0., -0.]], dtype=float32),
 False)

# Jordan_Gauss

In [20]:
mathlab.Jordan_Gauss(A2, B2)

Matrix:
1.0010000467300415*x1 + 2.000999927520752*x2 = [4.]
2.000999927520752*x1 + 3.997999906539917*x2 = [7.999]
матрица плохо обусловлена 26963.220703125


(array([[ 6.990098 ],
        [-1.4977952]], dtype=float32),
 ' норма матрицы 4.999400540677136',
 ' норма обратной матрицы 2496.4341045951387',
 False)

In [21]:
mathlab.Jordan_Gauss_proper(A1, B1)

Matrix:
1001/1000*x1 + 2001/1000*x2 = ['4']
2001/1000*x1 + 1999/500*x2 = ['7999/1000']
матрица плохо обусловлена 7599402017985157316695339/281897189175721984000


(array([[13999/2003],
        [-2999/2003]], dtype=object),
 ' норма матрицы 4.99940066407965',
 'обратная норма 2495.95639744366')

# Полная программа для вывода подходящей матрицы

In [22]:
def res():
    if not mathlab.Jacobi(A2, B2, 0.001)[4]:
        result = mathlab.Jordan_Gauss(A2, B2)
        if not mathlab.Jordan_Gauss(A2, B2)[4]:
            result = mathlab.Jordan_Gauss_proper(A1, B1)
            return result
        else:
            return result
    else:
        return mathlab.Jacobi(A2, B2, 0.001)
res()    

Matrix:
1.0010000467300415*x1 + 2.000999927520752*x2 = [4.]
2.000999927520752*x1 + 3.997999906539917*x2 = [7.999]
матрица плохо обусловлена 0.0
Matrix:
1.0010000467300415*x1 + 2.000999927520752*x2 = [4.]
2.000999927520752*x1 + 3.997999906539917*x2 = [7.999]
матрица плохо обусловлена 26963.220703125
Matrix:
1.0010000467300415*x1 + 2.000999927520752*x2 = [4.]
2.000999927520752*x1 + 3.997999906539917*x2 = [7.999]
матрица плохо обусловлена 26963.220703125


IndexError: tuple index out of range

In [ ]:
# print matrix
print("Matrix:" )
for i in range(A1.shape[0]):
    row = ["{}*x{}" .format(A1[i, j], j + 1) for j in range(A1.shape[1])]
    print(" + ".join(row), "=", B1[i])
print()

In [ ]:
from flask import Flask, render_template

app = Flask(__name__)

@app.route('/jacobi')
def index1():
    return f' СЛАУ методом Якоби: {mathlab.Jacobi(A, B, 0.001)}'

@app.route('/gauss')
def index2():
    return f' СЛАУ методом Жордана-Гаусса: {mathlab.Jordan_Gauss(A, B)}'

#@app.route('/care/')
#def index3():
    #name, age, profession = "Jerry", 24, 'Programmer'
    #template_context = dict(name=name, age=age, profession=profession)
    #return render_template('index.html', **template_context)



if __name__ == "__main__":
    app.run()

# Сравниваем время

 - Транспонирование

In [ ]:
st = perf_counter()
mathlab.T(list_massiv2)
en = perf_counter()
print(f'время выполнения {en-st}')

In [ ]:
st = perf_counter()
import numpy as np
for l in list_massiv2:
    np.transpose(l)
en = perf_counter()
print(f'время выполнения {en-st}')

Транспонирование: +- одинаковое время 

время выполнения 0.0003105999999206688

время выполнения 0.0003027999996447761

 - Определитель

In [ ]:
st = perf_counter()
mathlab.det(mt)
en = perf_counter()
print(f'время выполнения {en-st}')

In [ ]:
st = perf_counter()
for mt in list_of_massiv:
    np.linalg.det(mt)
en = perf_counter()
print(f'время выполнения {en-st}')

Определитель

время выполнения 0.009651500000018132

время выполнения 0.007707700000082696


 - Перемножение матриц

In [ ]:
st = perf_counter()
mathlab.M(m1, m2)
en = perf_counter()
print(f'время выполнения {en-st}')

In [ ]:
import numpy as np
st = perf_counter()
m1.dot(m2)
en = perf_counter()
print(f'время выполнения {en-st}')

Перемножение матриц

время выполнения 0.0008072999999058084

время выполнения 0.00029219999987617484

 - Деление на число

In [ ]:
st = perf_counter()
mathlab.divide(list_massiv2, 6, 5)
en = perf_counter()
print(f'время выполнения {en-st}')

In [ ]:
st = perf_counter()
for l in list_massiv2:
    l/5
en = perf_counter()
print(f'время выполнения {en-st}')

Деление на число

время выполнения 0.0007197000004453002

время выполнения 0.0061477999997805455

 - Сложение матриц

In [ ]:
st = perf_counter()
mathlab.add(list_massiv2, 3)
en = perf_counter()
print(f'время выполнения {en-st}')

In [ ]:
st = perf_counter()
np3 = np.add(list_massiv2[0], list_massiv2[1])
np.add(np3, list_massiv2[2])
en = perf_counter()
print(f'время выполнения {en-st}')

время выполнения 0.0007356000005529495

время выполнения 0.00030620000052294927

 - Максимум

In [ ]:
st = perf_counter()
mathlab.maximum(list_massiv2, 1)
mathlab.maximum(list_massiv2, 0)
en = perf_counter()
print(f'время выполнения {en-st}')

In [ ]:
st = perf_counter()
np.maximum(list_massiv2[0], list_massiv2[1])
en = perf_counter()
print(f'время выполнения {en-st}')

время выполнения 0.0004198000005999347

время выполнения 0.00021770000057586003